export interface Country {
  code: string;
  name: string;
  region: 'APAC' | 'EMEA' | 'LATAM' | 'NA';
}

export const REGION_LABELS: Record<Country['region'], string> = {
  APAC: "Asia Pacific",
  EMEA: "Europe, Middle East & Africa",
  LATAM: "Latin America",
  NA: "North America",
};

export const REGION_ORDER: Country['region'][] = ['APAC', 'EMEA', 'LATAM', 'NA'];

/** ISO country list grouped by business region, used for the practice's Region field */
export const COUNTRIES: Country[] = [
  { code: "as", name: "American Samoa", region: "APAC" },
  { code: "au", name: "Australia", region: "APAC" },
  { code: "bd", name: "Bangladesh", region: "APAC" },
  { code: "bt", name: "Bhutan", region: "APAC" },
  { code: "io", name: "British Indian Ocean Territory", region: "APAC" },
  { code: "bn", name: "Brunei Darussalam", region: "APAC" },
  { code: "kh", name: "Cambodia", region: "APAC" },
  { code: "cn", name: "China", region: "APAC" },
  { code: "cx", name: "Christmas Island", region: "APAC" },
  { code: "cc", name: "Cocos (Keeling) Islands", region: "APAC" },
  { code: "fj", name: "Fiji", region: "APAC" },
  { code: "gu", name: "Guam", region: "APAC" },
  { code: "hk", name: "Hong Kong", region: "APAC" },
  { code: "in", name: "India", region: "APAC" },
  { code: "id", name: "Indonesia", region: "APAC" },
  { code: "jp", name: "Japan", region: "APAC" },
  { code: "ki", name: "Kiribati", region: "APAC" },
  { code: "kp", name: "Korea, Democratic People's Republic of", region: "APAC" },
  { code: "kr", name: "Korea, Republic of", region: "APAC" },
  { code: "la", name: "Lao People's Democratic Republic", region: "APAC" },
  { code: "mo", name: "Macao", region: "APAC" },
  { code: "my", name: "Malaysia", region: "APAC" },
  { code: "mv", name: "Maldives", region: "APAC" },
  { code: "mh", name: "Marshall Islands", region: "APAC" },
  { code: "fm", name: "Micronesia, Federated States of", region: "APAC" },
  { code: "mn", name: "Mongolia", region: "APAC" },
  { code: "mm", name: "Myanmar", region: "APAC" },
  { code: "nr", name: "Nauru", region: "APAC" },
  { code: "np", name: "Nepal", region: "APAC" },
  { code: "nz", name: "New Zealand", region: "APAC" },
  { code: "nu", name: "Niue", region: "APAC" },
  { code: "nf", name: "Norfolk Island", region: "APAC" },
  { code: "mp", name: "Northern Mariana Islands", region: "APAC" },
  { code: "pk", name: "Pakistan", region: "APAC" },
  { code: "pw", name: "Palau", region: "APAC" },
  { code: "pg", name: "Papua New Guinea", region: "APAC" },
  { code: "ph", name: "Philippines", region: "APAC" },
  { code: "pn", name: "Pitcairn", region: "APAC" },
  { code: "ws", name: "Samoa", region: "APAC" },
  { code: "sg", name: "Singapore", region: "APAC" },
  { code: "sb", name: "Solomon Islands", region: "APAC" },
  { code: "lk", name: "Sri Lanka", region: "APAC" },
  { code: "tw", name: "Taiwan, Province of China", region: "APAC" },
  { code: "th", name: "Thailand", region: "APAC" },
  { code: "tl", name: "Timor-Leste", region: "APAC" },
  { code: "tk", name: "Tokelau", region: "APAC" },
  { code: "to", name: "Tonga", region: "APAC" },
  { code: "tv", name: "Tuvalu", region: "APAC" },
  { code: "um", name: "United States Minor Outlying Islands", region: "APAC" },
  { code: "vu", name: "Vanuatu", region: "APAC" },
  { code: "vn", name: "Vietnam", region: "APAC" },
  { code: "af", name: "Afghanistan", region: "EMEA" },
  { code: "al", name: "Albania", region: "EMEA" },
  { code: "dz", name: "Algeria", region: "EMEA" },
  { code: "ad", name: "Andorra", region: "EMEA" },
  { code: "ao", name: "Angola", region: "EMEA" },
  { code: "aq", name: "Antarctica", region: "EMEA" },
  { code: "am", name: "Armenia", region: "EMEA" },
  { code: "at", name: "Austria", region: "EMEA" },
  { code: "az", name: "Azerbaijan", region: "EMEA" },
  { code: "bh", name: "Bahrain", region: "EMEA" },
  { code: "by", name: "Belarus", region: "EMEA" },
  { code: "be", name: "Belgium", region: "EMEA" },
  { code: "bj", name: "Benin", region: "EMEA" },
  { code: "ba", name: "Bosnia and Herzegovina", region: "EMEA" },
  { code: "bw", name: "Botswana", region: "EMEA" },
  { code: "bv", name: "Bouvet Island", region: "EMEA" },
  { code: "bg", name: "Bulgaria", region: "EMEA" },
  { code: "bf", name: "Burkina Faso", region: "EMEA" },
  { code: "bi", name: "Burundi", region: "EMEA" },
  { code: "cv", name: "Cabo Verde", region: "EMEA" },
  { code: "cm", name: "Cameroon", region: "EMEA" },
  { code: "cf", name: "Central African Republic", region: "EMEA" },
  { code: "td", name: "Chad", region: "EMEA" },
  { code: "mf", name: "Collectivity of Saint Martin", region: "EMEA" },
  { code: "km", name: "Comoros", region: "EMEA" },
  { code: "cg", name: "Congo", region: "EMEA" },
  { code: "cd", name: "Congo, the Democratic Republic of the", region: "EMEA" },
  { code: "ck", name: "Cook Islands", region: "EMEA" },
  { code: "hr", name: "Croatia", region: "EMEA" },
  { code: "cw", name: "Curaçao", region: "EMEA" },
  { code: "cy", name: "Cyprus", region: "EMEA" },
  { code: "cz", name: "Czechia", region: "EMEA" },
  { code: "ci", name: "Côte d'Ivoire", region: "EMEA" },
  { code: "dk", name: "Denmark", region: "EMEA" },
  { code: "dj", name: "Djibouti", region: "EMEA" },
  { code: "eg", name: "Egypt", region: "EMEA" },
  { code: "gq", name: "Equatorial Guinea", region: "EMEA" },
  { code: "er", name: "Eritrea", region: "EMEA" },
  { code: "ee", name: "Estonia", region: "EMEA" },
  { code: "et", name: "Ethiopia", region: "EMEA" },
  { code: "fo", name: "Faroe Islands", region: "EMEA" },
  { code: "fi", name: "Finland", region: "EMEA" },
  { code: "fr", name: "France", region: "EMEA" },
  { code: "gf", name: "French Guiana", region: "EMEA" },
  { code: "pf", name: "French Polynesia", region: "EMEA" },
  { code: "tf", name: "French Southern Territories", region: "EMEA" },
  { code: "ga", name: "Gabon", region: "EMEA" },
  { code: "gm", name: "Gambia", region: "EMEA" },
  { code: "ge", name: "Georgia", region: "EMEA" },
  { code: "de", name: "Germany", region: "EMEA" },
  { code: "gh", name: "Ghana", region: "EMEA" },
  { code: "gi", name: "Gibralta", region: "EMEA" },
  { code: "gr", name: "Greece", region: "EMEA" },
  { code: "gl", name: "Greenland", region: "EMEA" },
  { code: "gp", name: "Guadeloupe", region: "EMEA" },
  { code: "gg", name: "Guernsey", region: "EMEA" },
  { code: "gn", name: "Guinea", region: "EMEA" },
  { code: "gw", name: "Guinea-Bissau", region: "EMEA" },
  { code: "hm", name: "Heard Island and McDonald Islands", region: "EMEA" },
  { code: "va", name: "Holy See", region: "EMEA" },
  { code: "hu", name: "Hungary", region: "EMEA" },
  { code: "is", name: "Iceland", region: "EMEA" },
  { code: "ir", name: "Iran, Islamic Republic of", region: "EMEA" },
  { code: "iq", name: "Iraq", region: "EMEA" },
  { code: "ie", name: "Ireland", region: "EMEA" },
  { code: "im", name: "Isle of Man", region: "EMEA" },
  { code: "il", name: "Israel", region: "EMEA" },
  { code: "it", name: "Italy", region: "EMEA" },
  { code: "je", name: "Jersey", region: "EMEA" },
  { code: "jo", name: "Jordan", region: "EMEA" },
  { code: "kz", name: "Kazakhstan", region: "EMEA" },
  { code: "ke", name: "Kenya", region: "EMEA" },
  { code: "kw", name: "Kuwait", region: "EMEA" },
  { code: "kg", name: "Kyrgyzstan", region: "EMEA" },
  { code: "lv", name: "Latvia", region: "EMEA" },
  { code: "lb", name: "Lebanon", region: "EMEA" },
  { code: "ls", name: "Lesotho", region: "EMEA" },
  { code: "lr", name: "Liberia", region: "EMEA" },
  { code: "ly", name: "Libya", region: "EMEA" },
  { code: "li", name: "Liechtenstein", region: "EMEA" },
  { code: "lt", name: "Lithuania", region: "EMEA" },
  { code: "lu", name: "Luxembourg", region: "EMEA" },
  { code: "mk", name: "Macedonia, the former Yugoslav Republic of", region: "EMEA" },
  { code: "mg", name: "Madagascar", region: "EMEA" },
  { code: "mw", name: "Malawi", region: "EMEA" },
  { code: "ml", name: "Mali", region: "EMEA" },
  { code: "mt", name: "Malta", region: "EMEA" },
  { code: "mq", name: "Martinique", region: "EMEA" },
  { code: "mr", name: "Mauritania", region: "EMEA" },
  { code: "mu", name: "Mauritius", region: "EMEA" },
  { code: "yt", name: "Mayotte", region: "EMEA" },
  { code: "md", name: "Moldova, Republic of", region: "EMEA" },
  { code: "mc", name: "Monaco", region: "EMEA" },
  { code: "me", name: "Montenegro", region: "EMEA" },
  { code: "ma", name: "Morocco", region: "EMEA" },
  { code: "mz", name: "Mozambique", region: "EMEA" },
  { code: "na", name: "Namibia", region: "EMEA" },
  { code: "nl", name: "Netherlands", region: "EMEA" },
  { code: "nc", name: "New Caledonia", region: "EMEA" },
  { code: "ne", name: "Niger", region: "EMEA" },
  { code: "ng", name: "Nigeria", region: "EMEA" },
  { code: "no", name: "Norway", region: "EMEA" },
  { code: "om", name: "Oman", region: "EMEA" },
  { code: "ps", name: "Palestine, State of", region: "EMEA" },
  { code: "pl", name: "Poland", region: "EMEA" },
  { code: "pt", name: "Portugal", region: "EMEA" },
  { code: "qa", name: "Qatar", region: "EMEA" },
  { code: "ro", name: "Romania", region: "EMEA" },
  { code: "ru", name: "Russian Federation", region: "EMEA" },
  { code: "rw", name: "Rwanda", region: "EMEA" },
  { code: "re", name: "Réunion", region: "EMEA" },
  { code: "bl", name: "Saint Barthélemy", region: "EMEA" },
  { code: "sh", name: "Saint Helena, Ascension and Tristan da Cunha", region: "EMEA" },
  { code: "pm", name: "Saint Pierre and Miquelon", region: "EMEA" },
  { code: "sm", name: "San Marino", region: "EMEA" },
  { code: "st", name: "Sao Tome and Principe", region: "EMEA" },
  { code: "sa", name: "Saudi Arabia", region: "EMEA" },
  { code: "sn", name: "Senegal", region: "EMEA" },
  { code: "rs", name: "Serbia", region: "EMEA" },
  { code: "sc", name: "Seychelles", region: "EMEA" },
  { code: "sl", name: "Sierra Leone", region: "EMEA" },
  { code: "sx", name: "Sint Maarten", region: "EMEA" },
  { code: "sk", name: "Slovakia", region: "EMEA" },
  { code: "si", name: "Slovenia", region: "EMEA" },
  { code: "so", name: "Somalia", region: "EMEA" },
  { code: "za", name: "South Africa", region: "EMEA" },
  { code: "ss", name: "South Sudan", region: "EMEA" },
  { code: "es", name: "Spain", region: "EMEA" },
  { code: "sd", name: "Sudan", region: "EMEA" },
  { code: "sj", name: "Svalbard and Jan Mayen", region: "EMEA" },
  { code: "sz", name: "Swaziland", region: "EMEA" },
  { code: "se", name: "Sweden", region: "EMEA" },
  { code: "ch", name: "Switzerland", region: "EMEA" },
  { code: "sy", name: "Syrian Arab Republic", region: "EMEA" },
  { code: "tj", name: "Tajikistan", region: "EMEA" },
  { code: "tz", name: "Tanzania, United Republic of", region: "EMEA" },
  { code: "tg", name: "Togo", region: "EMEA" },
  { code: "tn", name: "Tunisia", region: "EMEA" },
  { code: "tr", name: "Turkey", region: "EMEA" },
  { code: "tm", name: "Turkmenistan", region: "EMEA" },
  { code: "ug", name: "Uganda", region: "EMEA" },
  { code: "ua", name: "Ukraine", region: "EMEA" },
  { code: "ae", name: "United Arab Emirates", region: "EMEA" },
  { code: "gb", name: "United Kingdom of Great Britain and Northern Ireland", region: "EMEA" },
  { code: "uz", name: "Uzbekistan", region: "EMEA" },
  { code: "wf", name: "Wallis and Futuna", region: "EMEA" },
  { code: "eh", name: "Western Sahara", region: "EMEA" },
  { code: "ye", name: "Yemen", region: "EMEA" },
  { code: "zm", name: "Zambia", region: "EMEA" },
  { code: "zw", name: "Zimbabwe", region: "EMEA" },
  { code: "ax", name: "Åland Islands", region: "EMEA" },
  { code: "ai", name: "Anguilla", region: "LATAM" },
  { code: "ag", name: "Antigua and Barbuda", region: "LATAM" },
  { code: "ar", name: "Argentina", region: "LATAM" },
  { code: "aw", name: "Aruba", region: "LATAM" },
  { code: "bs", name: "Bahamas", region: "LATAM" },
  { code: "bb", name: "Barbados", region: "LATAM" },
  { code: "bz", name: "Belize", region: "LATAM" },
  { code: "bm", name: "Bermuda", region: "LATAM" },
  { code: "bo", name: "Bolivia, Plurinational State of", region: "LATAM" },
  { code: "br", name: "Brazil", region: "LATAM" },
  { code: "ky", name: "Cayman Islands", region: "LATAM" },
  { code: "cl", name: "Chile", region: "LATAM" },
  { code: "co", name: "Colombia", region: "LATAM" },
  { code: "cr", name: "Costa Rica", region: "LATAM" },
  { code: "cu", name: "Cuba", region: "LATAM" },
  { code: "dm", name: "Dominica", region: "LATAM" },
  { code: "do", name: "Dominican Republic", region: "LATAM" },
  { code: "ec", name: "Ecuador", region: "LATAM" },
  { code: "sv", name: "El Salvador", region: "LATAM" },
  { code: "fk", name: "Falkland Islands (Malvinas)", region: "LATAM" },
  { code: "gd", name: "Grenada", region: "LATAM" },
  { code: "gt", name: "Guatemala", region: "LATAM" },
  { code: "gy", name: "Guyana", region: "LATAM" },
  { code: "ht", name: "Haiti", region: "LATAM" },
  { code: "hn", name: "Honduras", region: "LATAM" },
  { code: "jm", name: "Jamaica", region: "LATAM" },
  { code: "mx", name: "Mexico", region: "LATAM" },
  { code: "ms", name: "Montserrat", region: "LATAM" },
  { code: "ni", name: "Nicaragua", region: "LATAM" },
  { code: "pa", name: "Panama", region: "LATAM" },
  { code: "py", name: "Paraguay", region: "LATAM" },
  { code: "pe", name: "Peru", region: "LATAM" },
  { code: "pr", name: "Puerto Rico", region: "LATAM" },
  { code: "kn", name: "Saint Kitts and Nevis", region: "LATAM" },
  { code: "lc", name: "Saint Lucia", region: "LATAM" },
  { code: "vc", name: "Saint Vincent and the Grenadines", region: "LATAM" },
  { code: "gs", name: "South Georgia and the South Sandwich Islands", region: "LATAM" },
  { code: "sr", name: "Suriname", region: "LATAM" },
  { code: "tt", name: "Trinidad and Tobago", region: "LATAM" },
  { code: "tc", name: "Turks and Caicos Islands", region: "LATAM" },
  { code: "uy", name: "Uruguay", region: "LATAM" },
  { code: "ve", name: "Venezuela, Bolivarian Republic of", region: "LATAM" },
  { code: "vg", name: "Virgin Islands, British", region: "LATAM" },
  { code: "vi", name: "Virgin Islands, U.S.", region: "LATAM" },
  { code: "ca", name: "Canada", region: "NA" },
  { code: "us", name: "United States of America", region: "NA" },
];
